In [72]:
from sklearn.datasets import load_boston
from  sklearn.metrics import confusion_matrix
from sklearn.preprocessing import StandardScaler
from sklearn.naive_bayes import GaussianNB
from sklearn.ensemble import AdaBoostClassifier
import pandas as pd
import numpy as np
import pandas as pd
from scipy.stats import ttest_1samp,wilcoxon,shapiro,ttest_ind,levene,bartlett,mannwhitneyu
import math
import matplotlib.pyplot as plt
import statsmodels.formula.api as sm
from statsmodels.formula.api import ols
%matplotlib inline
from statsmodels.stats.power import ttest_power
import seaborn as sns
from sklearn.linear_model import RidgeCV, LassoCV, Ridge, Lasso
from scipy.stats import f_oneway
from sklearn.linear_model import LinearRegression
from sklearn import metrics
from sklearn.model_selection import train_test_split
boston=load_boston()
from sklearn.metrics import classification_report,accuracy_score
import warnings
warnings.filterwarnings('ignore')
import statsmodels.api as smi
import statsmodels.tsa.api as smt
from scipy import stats
import statsmodels.stats.api as sms
import scipy.stats as stats
from statsmodels.graphics.gofplots import ProbPlot
import pylab
from sklearn.feature_selection import RFE
from statsmodels.compat import lzip
from statsmodels.stats.outliers_influence import variance_inflation_factor
from sklearn.model_selection import train_test_split
from sklearn.pipeline import make_pipeline
from imblearn.pipeline import make_pipeline as imbalanced_make_pipeline
from sklearn.preprocessing import LabelEncoder
from imblearn.over_sampling import SMOTE
from imblearn.under_sampling import NearMiss
from sklearn.metrics import precision_score, recall_score, f1_score, roc_auc_score, accuracy_score, classification_report
from collections import Counter
from sklearn.model_selection import KFold, StratifiedKFold
from sklearn.neighbors import KNeighborsClassifier
from sklearn import preprocessing
from sklearn.ensemble import BaggingClassifier
from sklearn.metrics import accuracy_score
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import OneHotEncoder
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import RandomizedSearchCV
from sklearn.model_selection import GridSearchCV

from sklearn.model_selection import cross_val_score
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import RandomizedSearchCV
from sklearn.tree import DecisionTreeClassifier

from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.ensemble import BaggingClassifier

In [3]:
df=pd.read_csv('C:/Users/Vikash_verma/Desktop/data science/datasets/data14.csv')

In [11]:
df=df.fillna(0,axis=1)

In [12]:
df

,Id,v2a1,hacdor,rooms,hacapo,v14a,refrig,v18q,v18q1,r4h1,...,SQBescolari,SQBage,SQBhogar_total,SQBedjefe,SQBhogar_nin,SQBovercrowding,SQBdependency,SQBmeaned,agesq,Target
0,ID_279628684,190000.0,0,3,0,1,1,0,0.0,0,...,100,1849,1,100,0,1.000000,0.000000,100.000000,1849,4
1,ID_f29eb3ddd,135000.0,0,4,0,1,1,1,1.0,0,...,144,4489,1,144,0,1.000000,64.000000,144.000000,4489,4
2,ID_68de51c94,0.0,0,8,0,1,1,0,0.0,0,...,121,8464,1,0,0,0.250000,64.000000,121.000000,8464,4
3,ID_d671db89c,180000.0,0,5,0,1,1,1,1.0,0,...,81,289,16,121,4,1.777778,1.000000,121.000000,289,4
4,ID_d56d6f5f5,180000.0,0,5,0,1,1,1,1.0,0,...,121,1369,16,121,4,1.777778,1.000000,121.000000,1369,4
5,ID_ec05b1a7b,180000.0,0,5,0,1,1,1,1.0,0,...,121,1444,16,121,4,1.777778,1.000000,121.000000,1444,4
6,ID_e9e0c1100,180000.0,0,5,0,1,1,1,1.0,0,...,4,64,16,121,4,1.777778,1.000000,121.000000,64,4
7,ID_3e04e571e,130000.0,1,2,0,1,1,0,0.0,0,...,0,49,16,81,4,16.000000,1.000000,100.000000,49,4
8,ID_1284f8aad,130000.0,1,2,0,1,1,0,0.0,0,...,81,900,16,81,4,16.000000,1.000000,100.000000,900,4
9,ID_51f52fdd2,130000.0,1,2,0,1,1,0,0.0,0,...,121,784,16,81,4,16.000000,1.000000,100.000000,784,4
10,ID_db44f5c59,130000.0,1,2,0,1,1,0,0.0,0,...,9,121,16,81,4,16.000000,1.000000,100.000000,121,4
11,ID_de822510c,100000.0,0,3,0,1,1,0,0.0,0,...,144,324,4,0,1,1.000000,1.000000,529.000000,324,4
12,ID_d94071d7c,100000.0,0,3,0,1,1,0,0.0,0,...,121,1156,4,0,1,1.000000,1.000000,529.000000,1156,4
13,ID_064b57869,0.0,0,4,0,1,1,1,1.0,0,...,16,6241,4,0,0,1.000000,1.000000,90.250000,6241,4
14,ID_5c837d8a4,0.0,0,4,0,1,1,1,1.0,0,...,225,1521,4,0,0,1.000000,1.000000,90.250000,1521,4
15,ID_0a39e419e,90000.0,1,2,0,1,1,0,0.0,0,...,121,361,16,0,4,16.000000,9.000000,289.000000,361,4
16,ID_4ff51f90c,90000.0,1,2,0,1,1,0,0.0,0,...,4,4900,16,0,4,16.000000,9.000000,289.000000,4900,4
17,ID_336c51386,90000.0,1,2,0,1,1,0,0.0,0,...,121,361,16,0,4,16.000000,9.000000,289.000000,361,4
18,ID_c51938edf,90000.0,1,2,0,1,1,0,0.0,0,...,100,2500,16,0,4,16.000000,9.000000,289.000000,2500,4
19,ID_35b66f7c6,215000.0,0,4,0,1,1,0,0.0,0,...,144,484,4,225,0,1.000000,0.000000,182.250000,484,4
20,ID_74a2bc523,215000.0,0,4,0,1,1,0,0.0,0,...,225,676,4,225,0,1.000000,0.000000,182.250000,676,4
21,ID_15d393ce7,150000.0,0,3,0,1,1,0,0.0,0,...,16,4761,4,16,0,4.000000,64.000000,100.000000,4761,4
22,ID_a0bff0ba7,150000.0,0,3,0,1,1,0,0.0,0,...,256,4356,4,16,0,4.000000,64.000000,100.000000,4356,4
23,ID_848b0fdf1,100000.0,1,1,1,0,1,0,0.0,0,...,36,1681,9,36,0,9.000000,0.000000,106.777770,1681,4
24,ID_298d857e5,100000.0,1,1,1,0,1,0,0.0,0,...,169,400,9,36,0,9.000000,0.000000,106.777770,400,4
25,ID_1d5bf8ddf,100000.0,1,1,1,0,1,0,0.0,0,...,144,1600,9,36,0,9.000000,0.000000,106.777770,1600,4
26,ID_e5cdba865,0.0,0,5,0,1,1,0,0.0,0,...,225,1936,1,225,0,0.250000,0.000000,225.000000,1936,4
27,ID_e18530139,120000.0,0,4,0,1,1,1,1.0,0,...,36,4761,9,36,0,2.250000,0.250000,44.444443,4761,4
28,ID_cba035c44,120000.0,0,4,0,1,1,1,1.0,0,...,36,3844,9,36,0,2.250000,0.250000,44.444443,3844,4
29,ID_b6c1c7e65,120000.0,0,4,0,1,1,1,1.0,0,...,64,1089,9,36,0,2.250000,0.250000,44.444443,1089,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9527,ID_92b30d94b,0.0,0,5,0,1,1,0,0.0,2,...,0,1,16,64,4,4.000000,1.000000,90.250000,1,4
9528,ID_6309f1595,45000.0,0,3,0,1,0,0,0.0,0,...,256,961,1,0,0,1.000000,0.000000,256.000000,961,4
9529,ID_f8b8c7703,0.0,0,1,0,1,1,0,0.0,0,...,36,2116,4,36,0,4.000000,0.000000,36.000000,2116,4
9530,ID_7226bda20,0.0,0,1,0,1,1,0,0.0,0,...,36,2704,4,36,0,4.000000,0.000000,36.000000,2704,4
9531,ID_10da2c3cb,70000.0,0,4,0,1,1,0,0.0,0,...,25,2916,9,25,1,2.250000,0.250000,30.250000,2916,4
9532,ID_503cfc817,70000.0,0,4,0,1,1,0,0.0,0,...,36,2025,9,25,1,2.250000,0.250000,30.250000,2025,4
9533,ID_5384717d3,70000.0,0,4,0,1,1,0,0.0,0,...,100,289,9,25,1,2.250000,0.250000,30.250000,289,4
9534,ID_8d3963fff,0.0,0,7,0,1,1,0,0.0,0,...,16,5476,1,16,0,0.111111,64.000000,16.000000,5476,3
9535,ID_18b0a845b,0.0,0,4,0,1,0,0,0.0,1,...,25,676,25,0,9,6.250000,2.250000,20.250000,676,1
9536,ID_d20bd7576,0.0,0,4,0,1,0,0,0.0,1,...,0,64,25,0,9,6.250000,2.250000,20.250000,64,2
9537,ID_cca751e53,0.0,0,4,0,1,0,0,0.0,1,...,16,841,25,0,9,6.250000,2.250000,20.250000,841,2
9538,ID_bfbb06d62,0.0,0,4,0,1,0,0,0.0,1,...,0,36,25,0,9,6.250000,2.250000,20.250000,36,2
9539,ID_e20c78904,0.0,0,4,0,1,0,0,0.0,1,...,0,36,25,0,9,6.250000,2.250000,20.250000,36,2
9540,ID_e01b00c7e,0.0,0,3,0,0,0,0,0.0,2,...,0,4,25,4,9,6.250000,2.250000,16.000000,4,2
9541,ID_a31274054,0.0,0,3,0,0,0,0,0.0,2,...,4,1600,25,4,9,6.250000,2.250000,16.000000,1600,2
9542,ID_fc386a944,0.0,0,3,0,0,0,0,0.0,2,...,9,100,25,4,9,6.250000,2.250000,16.000000,100,2
9543,ID_2f8268634,0.0,0,3,0,0,0,0,0.0,2,...,36,169,25,4,9,6.250000,2.250000,16.000000,169,2
9544,ID_4c180d79f,0.0,0,3,0,0,0,0,0.0,2,...,36,1089,25,4,9,6.250000,2.250000,16.000000,1089,2
9545,ID_32a00a8bf,46500.0,0,5,0,1,1,0,0.0,1,...,4,2025,25,4,4,5.444444,0.444444,100.000000,2025,4
9546,ID_1dfb12fcf,46500.0,0,5,0,1,1,0,0.0,1,...,36,2116,25,4,4,5.444444,0.444444,100.000000,2116,4
9547,ID_198be48d1,46500.0,0,5,0,1,1,0,0.0,1,...,121,529,25,4,4,5.444444,0.444444,100.000000,529,4
9548,ID_9df63c33e,46500.0,0,5,0,1,1,0,0.0,1,...,121,324,25,4,4,5.444444,0.444444,100.000000,324,4
9549,ID_aacac04a2,46500.0,0,5,0,1,1,0,0.0,1,...,0,4,25,4,4,5.444444,0.444444,100.000000,4,4
9550,ID_90a399a51,0.0,0,3,0,1,1,0,0.0,0,...,36,3721,4,0,0,4.000000,1.000000,9.000000,3721,2
9551,ID_79d39dddc,0.0,0,3,0,1,1,0,0.0,0,...,0,4489,4,0,0,4.000000,1.000000,9.000000,4489,2
9552,ID_d45ae367d,80000.0,0,6,0,1,1,0,0.0,0,...,81,2116,25,81,1,1.562500,0.062500,68.062500,2116,2
9553,ID_c94744e07,80000.0,0,6,0,1,1,0,0.0,0,...,0,4,25,81,1,1.562500,0.062500,68.062500,4,2
9554,ID_85fc658f8,80000.0,0,6,0,1,1,0,0.0,0,...,25,2500,25,81,1,1.562500,0.062500,68.062500,2500,2
9555,ID_ced540c61,80000.0,0,6,0,1,1,0,0.0,0,...,121,676,25,81,1,1.562500,0.062500,68.062500,676,2
9556,ID_a38c64491,80000.0,0,6,0,1,1,0,0.0,0,...,64,441,25,81,1,1.562500,0.062500,68.062500,441,2

In [36]:
x=df.iloc[:,1:-1]
y=df.Target

# Replace all the Yes and No values with 1 and respectively

In [37]:
x.loc[:,'dependency'].replace(to_replace=dict(yes=1,no=0),inplace=True)
x.loc[:,'edjefe'].replace(to_replace=dict(yes=1,no=0),inplace=True)
x.loc[:,'edjefa'].replace(to_replace=dict(yes=1,no=0),inplace=True)

In [38]:
x.head()

,v2a1,hacdor,rooms,hacapo,v14a,refrig,v18q,v18q1,r4h1,r4h2,...,age,SQBescolari,SQBage,SQBhogar_total,SQBedjefe,SQBhogar_nin,SQBovercrowding,SQBdependency,SQBmeaned,agesq
0,190000.0,0,3,0,1,1,0,0.0,0,1,...,43,100,1849,1,100,0,1.000000,0.0,100.0,1849
1,135000.0,0,4,0,1,1,1,1.0,0,1,...,67,144,4489,1,144,0,1.000000,64.0,144.0,4489
2,0.0,0,8,0,1,1,0,0.0,0,0,...,92,121,8464,1,0,0,0.250000,64.0,121.0,8464
3,180000.0,0,5,0,1,1,1,1.0,0,2,...,17,81,289,16,121,4,1.777778,1.0,121.0,289
4,180000.0,0,5,0,1,1,1,1.0,0,2,...,37,121,1369,16,121,4,1.777778,1.0,121.0,1369

# column 'idhogar'is a categorical value as there are multiple households with the same level

In [59]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
x.loc[:,'idhogar']=le.fit_transform(x.loc[:,'idhogar'])

In [60]:
x_test,x_train,y_test,y_train=train_test_split(x,y,random_state=0,train_size=0.2)

In [64]:
x_train.head()

,v2a1,hacdor,rooms,hacapo,v14a,refrig,v18q,v18q1,r4h1,r4h2,...,age,SQBescolari,SQBage,SQBhogar_total,SQBedjefe,SQBhogar_nin,SQBovercrowding,SQBdependency,SQBmeaned,agesq
4319,0.0,0,6,0,1,1,0,0.0,0,2,...,25,121,625,16,0,1,1.777778,0.111111,87.111107,625
3883,0.0,0,4,0,1,1,1,1.0,0,0,...,57,196,3249,4,0,0,1.000000,0.000000,196.000000,3249
3775,180000.0,0,4,0,1,1,1,2.0,1,1,...,39,225,1521,16,225,4,4.000000,1.000000,240.250000,1521
1519,0.0,0,5,0,1,1,1,2.0,0,1,...,19,144,361,9,0,4,1.000000,4.000000,784.000000,361
8810,0.0,0,4,0,1,1,0,0.0,1,1,...,11,25,121,16,81,4,4.000000,1.000000,90.250000,121

In [67]:
#feature scaling the test and train set
from sklearn.preprocessing import StandardScaler
sc_X=StandardScaler()
X_train=sc_X.fit_transform(x_train)
X_test=sc_X.transform(x_test)

In [68]:
from sklearn import tree
from sklearn.ensemble import BaggingClassifier
model=BaggingClassifier(tree.DecisionTreeClassifier(random_state=1))
model.fit(x_train,y_train)
print(model.score(x_train,y_train))
y_pred=model.predict(x_test)
cm=confusion_matrix(y_test,y_pred)

0.9976458278838608

In [69]:
cm

array([[ 121,    6,    0,    9],
       [   6,  284,   10,   20],
       [   2,   16,  178,   17],
       [   9,   10,    8, 1215]], dtype=int64)

In [70]:
model_1=RandomForestClassifier(random_state=1)
model_1.fit(x_train,y_train)
model_1.score(x_test,y_test)

0.9162742019884877

In [74]:
model_2=AdaBoostClassifier(random_state=1)
model_2.fit(x_train,y_train)
model_2.score(x_test,y_test)

0.6823652537938252

In [76]:
from sklearn.ensemble import  GradientBoostingClassifier
model_3=GradientBoostingClassifier(learning_rate=0.01,random_state=1)
model_3.fit(x_train,y_train)
model_3.score(x_test,y_test)

0.6985871271585558